### ISSUE TITLE
Include dependencies in repo or add installer?

### ISSUE THREAD

**Issue by boogheta** [libe-sixplus/graph-explorer#1]
When one wants to try and use the code, he currently has to manually download all dependencies and place/name them accordingly to what he can read in index.html, having for instance a package.json to be able to install with `npm install` would be nice

**Comment by paulloz** [comment]
Sure! I'm cleaning the repository right now. A `package.json` is on its way :shipit:.

**Comment by paulloz** [comment]
@boogheta [Here it is](https://github.com/libe-sixplus/graph-explorer/commit/da743c5c11cef51930734361dce2478167957fd9)!

**Comment by boogheta** [comment]
Great! Thank u!

**Comment by boogheta** [comment]
Great! Thank u!
